-- Fix Privileges for Olympus Analytics Setup
-- Execute this script as ACCOUNTADMIN or have an ACCOUNTADMIN run it for you

-- Switch to ACCOUNTADMIN role (required for granting privileges)
USE ROLE ACCOUNTADMIN;

-- Grant necessary privileges to SYSADMIN role
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SYSADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE XS_WAREHOUSE TO ROLE SYSADMIN;
GRANT OPERATE ON WAREHOUSE XS_WAREHOUSE TO ROLE SYSADMIN;

-- If the database already exists, grant ownership to SYSADMIN
GRANT OWNERSHIP ON DATABASE OLYMPUS_ANALYTICS TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Grant schema privileges
GRANT OWNERSHIP ON SCHEMA OLYMPUS_ANALYTICS.BRONZE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA OLYMPUS_ANALYTICS.SILVER TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA OLYMPUS_ANALYTICS.GOLD TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA OLYMPUS_ANALYTICS.STAGING TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Grant all privileges on future objects
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA OLYMPUS_ANALYTICS.BRONZE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA OLYMPUS_ANALYTICS.SILVER TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA OLYMPUS_ANALYTICS.GOLD TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA OLYMPUS_ANALYTICS.STAGING TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA OLYMPUS_ANALYTICS.BRONZE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA OLYMPUS_ANALYTICS.SILVER TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA OLYMPUS_ANALYTICS.GOLD TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA OLYMPUS_ANALYTICS.STAGING TO ROLE SYSADMIN;

-- Grant privileges on future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA OLYMPUS_ANALYTICS.BRONZE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA OLYMPUS_ANALYTICS.SILVER TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA OLYMPUS_ANALYTICS.GOLD TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA OLYMPUS_ANALYTICS.STAGING TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA OLYMPUS_ANALYTICS.BRONZE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA OLYMPUS_ANALYTICS.SILVER TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA OLYMPUS_ANALYTICS.GOLD TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA OLYMPUS_ANALYTICS.STAGING TO ROLE SYSADMIN;

-- Switch back to SYSADMIN role
USE ROLE SYSADMIN;

-- Verify privileges
SHOW GRANTS TO ROLE SYSADMIN;

-- Test database creation (should work now)
SELECT CURRENT_ROLE(), CURRENT_USER(), CURRENT_WAREHOUSE();