name: 'olympus_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'olympus_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  olympus_analytics:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      +materialized: table
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  # dbt project variables
  start_date: '2024-01-01'
  end_date: '2025-12-31'



# Seeds configuration
seeds:
  olympus_analytics:
    +schema: bronze
    +quote_columns: false

# Tests configuration
tests:
  +store_failures: true
  +schema: tests

# Snapshots configuration
snapshots:
  olympus_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at